import 'package:flutter/material.dart';

// ── Main styles ──────────────────────────────────────────────────────────────
import 'package:re_highlight/styles/a11y-dark.dart';
import 'package:re_highlight/styles/a11y-light.dart';
import 'package:re_highlight/styles/agate.dart';
import 'package:re_highlight/styles/an-old-hope.dart';
import 'package:re_highlight/styles/androidstudio.dart';
import 'package:re_highlight/styles/arduino-light.dart';
import 'package:re_highlight/styles/arta.dart';
import 'package:re_highlight/styles/ascetic.dart';
import 'package:re_highlight/styles/atom-one-dark-reasonable.dart';
import 'package:re_highlight/styles/atom-one-dark.dart';
import 'package:re_highlight/styles/atom-one-light.dart';
import 'package:re_highlight/styles/brown-paper.dart';
import 'package:re_highlight/styles/codepen-embed.dart';
import 'package:re_highlight/styles/color-brewer.dart';
import 'package:re_highlight/styles/dark.dart';
import 'package:re_highlight/styles/default.dart';
import 'package:re_highlight/styles/devibeans.dart';
import 'package:re_highlight/styles/docco.dart';
import 'package:re_highlight/styles/far.dart';
import 'package:re_highlight/styles/felipec.dart';
import 'package:re_highlight/styles/foundation.dart';
import 'package:re_highlight/styles/github-dark-dimmed.dart';
import 'package:re_highlight/styles/github-dark.dart';
import 'package:re_highlight/styles/github.dart' as main_github;
import 'package:re_highlight/styles/gml.dart';
import 'package:re_highlight/styles/googlecode.dart';
import 'package:re_highlight/styles/gradient-dark.dart';
import 'package:re_highlight/styles/gradient-light.dart';
import 'package:re_highlight/styles/grayscale.dart';
import 'package:re_highlight/styles/hybrid.dart';
import 'package:re_highlight/styles/idea.dart';
import 'package:re_highlight/styles/intellij-light.dart';
import 'package:re_highlight/styles/ir-black.dart' as main_ir_black;
import 'package:re_highlight/styles/isbl-editor-dark.dart';
import 'package:re_highlight/styles/isbl-editor-light.dart';
import 'package:re_highlight/styles/kimbie-dark.dart';
import 'package:re_highlight/styles/kimbie-light.dart';
import 'package:re_highlight/styles/lightfair.dart';
import 'package:re_highlight/styles/lioshi.dart';
import 'package:re_highlight/styles/magula.dart';
import 'package:re_highlight/styles/mono-blue.dart';
import 'package:re_highlight/styles/monokai-sublime.dart';
import 'package:re_highlight/styles/monokai.dart' as main_monokai;
import 'package:re_highlight/styles/night-owl.dart';
import 'package:re_highlight/styles/nnfx-dark.dart';
import 'package:re_highlight/styles/nnfx-light.dart';
import 'package:re_highlight/styles/nord.dart' as main_nord;
import 'package:re_highlight/styles/obsidian.dart';
import 'package:re_highlight/styles/panda-syntax-dark.dart';
import 'package:re_highlight/styles/panda-syntax-light.dart';
import 'package:re_highlight/styles/paraiso-dark.dart';
import 'package:re_highlight/styles/paraiso-light.dart';
import 'package:re_highlight/styles/pojoaque.dart';
import 'package:re_highlight/styles/purebasic.dart';
import 'package:re_highlight/styles/qtcreator-dark.dart';
import 'package:re_highlight/styles/qtcreator-light.dart';
import 'package:re_highlight/styles/rainbow.dart';
import 'package:re_highlight/styles/routeros.dart';
import 'package:re_highlight/styles/school-book.dart';
import 'package:re_highlight/styles/shades-of-purple.dart';
import 'package:re_highlight/styles/srcery.dart';
import 'package:re_highlight/styles/stackoverflow-dark.dart';
import 'package:re_highlight/styles/stackoverflow-light.dart';
import 'package:re_highlight/styles/sunburst.dart';
import 'package:re_highlight/styles/tokyo-night-dark.dart';
import 'package:re_highlight/styles/tokyo-night-light.dart';
import 'package:re_highlight/styles/tomorrow-night-blue.dart';
import 'package:re_highlight/styles/tomorrow-night-bright.dart';
import 'package:re_highlight/styles/vs.dart';
import 'package:re_highlight/styles/vs2015.dart';
import 'package:re_highlight/styles/xcode.dart';
import 'package:re_highlight/styles/xt256.dart';

// ── Base16 styles ─────────────────────────────────────────────────────────────
import 'package:re_highlight/styles/base16/apathy.dart';
import 'package:re_highlight/styles/base16/apprentice.dart';
import 'package:re_highlight/styles/base16/ashes.dart';
import 'package:re_highlight/styles/base16/atelier-cave-light.dart';
import 'package:re_highlight/styles/base16/atelier-cave.dart';
import 'package:re_highlight/styles/base16/atelier-dune-light.dart';
import 'package:re_highlight/styles/base16/atelier-dune.dart';
import 'package:re_highlight/styles/base16/atelier-estuary-light.dart';
import 'package:re_highlight/styles/base16/atelier-estuary.dart';
import 'package:re_highlight/styles/base16/atelier-forest-light.dart';
import 'package:re_highlight/styles/base16/atelier-forest.dart';
import 'package:re_highlight/styles/base16/atelier-heath-light.dart';
import 'package:re_highlight/styles/base16/atelier-heath.dart';
import 'package:re_highlight/styles/base16/atelier-lakeside-light.dart';
import 'package:re_highlight/styles/base16/atelier-lakeside.dart';
import 'package:re_highlight/styles/base16/atelier-plateau-light.dart';
import 'package:re_highlight/styles/base16/atelier-plateau.dart';
import 'package:re_highlight/styles/base16/atelier-savanna-light.dart';
import 'package:re_highlight/styles/base16/atelier-savanna.dart';
import 'package:re_highlight/styles/base16/atelier-seaside-light.dart';
import 'package:re_highlight/styles/base16/atelier-seaside.dart';
import 'package:re_highlight/styles/base16/atelier-sulphurpool-light.dart';
import 'package:re_highlight/styles/base16/atelier-sulphurpool.dart';
import 'package:re_highlight/styles/base16/atlas.dart';
import 'package:re_highlight/styles/base16/bespin.dart';
import 'package:re_highlight/styles/base16/black-metal-bathory.dart';
import 'package:re_highlight/styles/base16/black-metal-burzum.dart';
import 'package:re_highlight/styles/base16/black-metal-dark-funeral.dart';
import 'package:re_highlight/styles/base16/black-metal-gorgoroth.dart';
import 'package:re_highlight/styles/base16/black-metal-immortal.dart';
import 'package:re_highlight/styles/base16/black-metal-khold.dart';
import 'package:re_highlight/styles/base16/black-metal-marduk.dart';
import 'package:re_highlight/styles/base16/black-metal-mayhem.dart';
import 'package:re_highlight/styles/base16/black-metal-nile.dart';
import 'package:re_highlight/styles/base16/black-metal-venom.dart';
import 'package:re_highlight/styles/base16/black-metal.dart';
import 'package:re_highlight/styles/base16/brewer.dart';
import 'package:re_highlight/styles/base16/bright.dart';
import 'package:re_highlight/styles/base16/brogrammer.dart';
import 'package:re_highlight/styles/base16/brush-trees-dark.dart';
import 'package:re_highlight/styles/base16/brush-trees.dart';
import 'package:re_highlight/styles/base16/chalk.dart';
import 'package:re_highlight/styles/base16/circus.dart';
import 'package:re_highlight/styles/base16/classic-dark.dart';
import 'package:re_highlight/styles/base16/classic-light.dart';
import 'package:re_highlight/styles/base16/codeschool.dart';
import 'package:re_highlight/styles/base16/colors.dart';
import 'package:re_highlight/styles/base16/cupcake.dart';
import 'package:re_highlight/styles/base16/cupertino.dart';
import 'package:re_highlight/styles/base16/danqing.dart';
import 'package:re_highlight/styles/base16/darcula.dart';
import 'package:re_highlight/styles/base16/dark-violet.dart';
import 'package:re_highlight/styles/base16/darkmoss.dart';
import 'package:re_highlight/styles/base16/darktooth.dart';
import 'package:re_highlight/styles/base16/decaf.dart';
import 'package:re_highlight/styles/base16/default-dark.dart';
import 'package:re_highlight/styles/base16/default-light.dart';
import 'package:re_highlight/styles/base16/dirtysea.dart';
import 'package:re_highlight/styles/base16/dracula.dart';
import 'package:re_highlight/styles/base16/edge-dark.dart';
import 'package:re_highlight/styles/base16/edge-light.dart';
import 'package:re_highlight/styles/base16/eighties.dart';
import 'package:re_highlight/styles/base16/embers.dart';
import 'package:re_highlight/styles/base16/equilibrium-dark.dart';
import 'package:re_highlight/styles/base16/equilibrium-gray-dark.dart';
import 'package:re_highlight/styles/base16/equilibrium-gray-light.dart';
import 'package:re_highlight/styles/base16/equilibrium-light.dart';
import 'package:re_highlight/styles/base16/espresso.dart';
import 'package:re_highlight/styles/base16/eva-dim.dart';
import 'package:re_highlight/styles/base16/eva.dart';
import 'package:re_highlight/styles/base16/flat.dart';
import 'package:re_highlight/styles/base16/framer.dart';
import 'package:re_highlight/styles/base16/fruit-soda.dart';
import 'package:re_highlight/styles/base16/gigavolt.dart';
import 'package:re_highlight/styles/base16/github.dart' as b16_github;
import 'package:re_highlight/styles/base16/google-dark.dart';
import 'package:re_highlight/styles/base16/google-light.dart';
import 'package:re_highlight/styles/base16/grayscale-dark.dart';
import 'package:re_highlight/styles/base16/grayscale-light.dart';
import 'package:re_highlight/styles/base16/green-screen.dart';
import 'package:re_highlight/styles/base16/gruvbox-dark-hard.dart';
import 'package:re_highlight/styles/base16/gruvbox-dark-medium.dart';
import 'package:re_highlight/styles/base16/gruvbox-dark-pale.dart';
import 'package:re_highlight/styles/base16/gruvbox-dark-soft.dart';
import 'package:re_highlight/styles/base16/gruvbox-light-hard.dart';
import 'package:re_highlight/styles/base16/gruvbox-light-medium.dart';
import 'package:re_highlight/styles/base16/gruvbox-light-soft.dart';
import 'package:re_highlight/styles/base16/hardcore.dart';
import 'package:re_highlight/styles/base16/harmonic16-dark.dart';
import 'package:re_highlight/styles/base16/harmonic16-light.dart';
import 'package:re_highlight/styles/base16/heetch-dark.dart';
import 'package:re_highlight/styles/base16/heetch-light.dart';
import 'package:re_highlight/styles/base16/helios.dart';
import 'package:re_highlight/styles/base16/hopscotch.dart';
import 'package:re_highlight/styles/base16/horizon-dark.dart';
import 'package:re_highlight/styles/base16/horizon-light.dart';
import 'package:re_highlight/styles/base16/humanoid-dark.dart';
import 'package:re_highlight/styles/base16/humanoid-light.dart';
import 'package:re_highlight/styles/base16/ia-dark.dart';
import 'package:re_highlight/styles/base16/ia-light.dart';
import 'package:re_highlight/styles/base16/icy-dark.dart';
import 'package:re_highlight/styles/base16/ir-black.dart' as b16_ir_black;
import 'package:re_highlight/styles/base16/isotope.dart';
import 'package:re_highlight/styles/base16/kimber.dart';
import 'package:re_highlight/styles/base16/london-tube.dart';
import 'package:re_highlight/styles/base16/macintosh.dart';
import 'package:re_highlight/styles/base16/marrakesh.dart';
import 'package:re_highlight/styles/base16/materia.dart';
import 'package:re_highlight/styles/base16/material-darker.dart';
import 'package:re_highlight/styles/base16/material-lighter.dart';
import 'package:re_highlight/styles/base16/material-palenight.dart';
import 'package:re_highlight/styles/base16/material-vivid.dart';
import 'package:re_highlight/styles/base16/material.dart';
import 'package:re_highlight/styles/base16/mellow-purple.dart';
import 'package:re_highlight/styles/base16/mexico-light.dart';
import 'package:re_highlight/styles/base16/mocha.dart';
import 'package:re_highlight/styles/base16/monokai.dart' as b16_monokai;
import 'package:re_highlight/styles/base16/nebula.dart';
import 'package:re_highlight/styles/base16/nord.dart' as b16_nord;
import 'package:re_highlight/styles/base16/nova.dart';
import 'package:re_highlight/styles/base16/ocean.dart';
import 'package:re_highlight/styles/base16/oceanicnext.dart';
import 'package:re_highlight/styles/base16/one-light.dart';
import 'package:re_highlight/styles/base16/onedark.dart';
import 'package:re_highlight/styles/base16/outrun-dark.dart';
import 'package:re_highlight/styles/base16/papercolor-dark.dart';
import 'package:re_highlight/styles/base16/papercolor-light.dart';
import 'package:re_highlight/styles/base16/paraiso.dart';
import 'package:re_highlight/styles/base16/pasque.dart';
import 'package:re_highlight/styles/base16/phd.dart';
import 'package:re_highlight/styles/base16/pico.dart';
import 'package:re_highlight/styles/base16/pop.dart';
import 'package:re_highlight/styles/base16/porple.dart';
import 'package:re_highlight/styles/base16/qualia.dart';
import 'package:re_highlight/styles/base16/railscasts.dart';
import 'package:re_highlight/styles/base16/rebecca.dart';
import 'package:re_highlight/styles/base16/ros-pine-dawn.dart';
import 'package:re_highlight/styles/base16/ros-pine-moon.dart';
import 'package:re_highlight/styles/base16/ros-pine.dart';
import 'package:re_highlight/styles/base16/sagelight.dart';
import 'package:re_highlight/styles/base16/sandcastle.dart';
import 'package:re_highlight/styles/base16/seti-ui.dart';
import 'package:re_highlight/styles/base16/shapeshifter.dart';
import 'package:re_highlight/styles/base16/silk-dark.dart';
import 'package:re_highlight/styles/base16/silk-light.dart';
import 'package:re_highlight/styles/base16/snazzy.dart';
import 'package:re_highlight/styles/base16/solar-flare-light.dart';
import 'package:re_highlight/styles/base16/solar-flare.dart';
import 'package:re_highlight/styles/base16/solarized-dark.dart';
import 'package:re_highlight/styles/base16/solarized-light.dart';
import 'package:re_highlight/styles/base16/spacemacs.dart';
import 'package:re_highlight/styles/base16/summercamp.dart';
import 'package:re_highlight/styles/base16/summerfruit-dark.dart';
import 'package:re_highlight/styles/base16/summerfruit-light.dart';
import 'package:re_highlight/styles/base16/synth-midnight-terminal-dark.dart';
import 'package:re_highlight/styles/base16/synth-midnight-terminal-light.dart';
import 'package:re_highlight/styles/base16/tango.dart';
import 'package:re_highlight/styles/base16/tender.dart';
import 'package:re_highlight/styles/base16/tomorrow-night.dart';
import 'package:re_highlight/styles/base16/tomorrow.dart';
import 'package:re_highlight/styles/base16/twilight.dart';
import 'package:re_highlight/styles/base16/unikitty-dark.dart';
import 'package:re_highlight/styles/base16/unikitty-light.dart';
import 'package:re_highlight/styles/base16/vulcan.dart';
import 'package:re_highlight/styles/base16/windows-10-light.dart';
import 'package:re_highlight/styles/base16/windows-10.dart';
import 'package:re_highlight/styles/base16/windows-95-light.dart';
import 'package:re_highlight/styles/base16/windows-95.dart';
import 'package:re_highlight/styles/base16/windows-high-contrast-light.dart';
import 'package:re_highlight/styles/base16/windows-high-contrast.dart';
import 'package:re_highlight/styles/base16/windows-nt-light.dart';
import 'package:re_highlight/styles/base16/windows-nt.dart';
import 'package:re_highlight/styles/base16/woodland.dart';
import 'package:re_highlight/styles/base16/xcode-dusk.dart';
import 'package:re_highlight/styles/base16/zenburn.dart';

/// Catálogo completo de temas de re_highlight como constantes estáticas.
///
abstract final class MarkastCodeThemes {
  // ── Dark ──────────────────────────────────────────────────────────────────

  static const Map<String, TextStyle> a11yDark             = a11YDarkTheme;
  static const Map<String, TextStyle> agate                = agateTheme;
  static const Map<String, TextStyle> anOldHope            = anOldHopeTheme;
  static const Map<String, TextStyle> androidStudio        = androidstudioTheme;
  static const Map<String, TextStyle> arta                 = artaTheme;
  static const Map<String, TextStyle> atomOneDark          = atomOneDarkTheme;
  static const Map<String, TextStyle> atomOneDarkReasonable= atomOneDarkReasonableTheme;
  static const Map<String, TextStyle> codepenEmbed         = codepenEmbedTheme;
  static const Map<String, TextStyle> dark                 = darkTheme;
  static const Map<String, TextStyle> devibeans            = devibeansTheme;
  static const Map<String, TextStyle> far                  = farTheme;
  static const Map<String, TextStyle> felipec              = felipecTheme;
  static const Map<String, TextStyle> githubDark           = githubDarkTheme;
  static const Map<String, TextStyle> githubDarkDimmed     = githubDarkDimmedTheme;
  static const Map<String, TextStyle> gradientDark         = gradientDarkTheme;
  static const Map<String, TextStyle> hybrid               = hybridTheme;
  static const Map<String, TextStyle> irBlack              = main_ir_black.irBlackTheme;
  static const Map<String, TextStyle> isblEditorDark       = isblEditorDarkTheme;
  static const Map<String, TextStyle> kimbieDark           = kimbieDarkTheme;
  static const Map<String, TextStyle> lioshi               = lioshiTheme;
  static const Map<String, TextStyle> monokai              = main_monokai.monokaiTheme;
  static const Map<String, TextStyle> monokaiSublime       = monokaiSublimeTheme;
  static const Map<String, TextStyle> nightOwl             = nightOwlTheme;
  static const Map<String, TextStyle> nnfxDark             = nnfxDarkTheme;
  static const Map<String, TextStyle> nord                 = main_nord.nordTheme;
  static const Map<String, TextStyle> obsidian             = obsidianTheme;
  static const Map<String, TextStyle> pandaSyntaxDark      = pandaSyntaxDarkTheme;
  static const Map<String, TextStyle> paraisoDark          = paraisoDarkTheme;
  static const Map<String, TextStyle> qtcreatorDark        = qtcreatorDarkTheme;
  static const Map<String, TextStyle> rainbow              = rainbowTheme;
  static const Map<String, TextStyle> shadesOfPurple       = shadesOfPurpleTheme;
  static const Map<String, TextStyle> srcery               = srceryTheme;
  static const Map<String, TextStyle> stackoverflowDark    = stackoverflowDarkTheme;
  static const Map<String, TextStyle> sunburst             = sunburstTheme;
  static const Map<String, TextStyle> tokyoNightDark       = tokyoNightDarkTheme;
  static const Map<String, TextStyle> tomorrowNightBlue    = tomorrowNightBlueTheme;
  static const Map<String, TextStyle> tomorrowNightBright  = tomorrowNightBrightTheme;
  static const Map<String, TextStyle> vs2015               = vs2015Theme;
  static const Map<String, TextStyle> xt256                = xt256Theme;

  // ── Light ─────────────────────────────────────────────────────────────────

  static const Map<String, TextStyle> a11yLight            = a11YLightTheme;
  static const Map<String, TextStyle> arduinoLight         = arduinoLightTheme;
  static const Map<String, TextStyle> ascetic              = asceticTheme;
  static const Map<String, TextStyle> atomOneLight         = atomOneLightTheme;
  static const Map<String, TextStyle> brownPaper           = brownPaperTheme;
  static const Map<String, TextStyle> colorBrewer          = colorBrewerTheme;
  static const Map<String, TextStyle> defaultLight         = defaultTheme;
  static const Map<String, TextStyle> docco                = doccoTheme;
  static const Map<String, TextStyle> foundation           = foundationTheme;
  static const Map<String, TextStyle> github               = main_github.githubTheme;
  static const Map<String, TextStyle> gml                  = gmlTheme;
  static const Map<String, TextStyle> googlecode           = googlecodeTheme;
  static const Map<String, TextStyle> gradientLight        = gradientLightTheme;
  static const Map<String, TextStyle> grayscale            = grayscaleTheme;
  static const Map<String, TextStyle> idea                 = ideaTheme;
  static const Map<String, TextStyle> intellijLight        = intellijLightTheme;
  static const Map<String, TextStyle> isblEditorLight      = isblEditorLightTheme;
  static const Map<String, TextStyle> kimbieLight          = kimbieLightTheme;
  static const Map<String, TextStyle> lightfair            = lightfairTheme;
  static const Map<String, TextStyle> magula               = magulaTheme;
  static const Map<String, TextStyle> monoBlue             = monoBlueTheme;
  static const Map<String, TextStyle> nnfxLight            = nnfxLightTheme;
  static const Map<String, TextStyle> pandaSyntaxLight     = pandaSyntaxLightTheme;
  static const Map<String, TextStyle> paraisoLight         = paraisoLightTheme;
  static const Map<String, TextStyle> pojoaque             = pojoaqueTheme;
  static const Map<String, TextStyle> purebasic            = purebasicTheme;
  static const Map<String, TextStyle> qtcreatorLight       = qtcreatorLightTheme;
  static const Map<String, TextStyle> routeros             = routerosTheme;
  static const Map<String, TextStyle> schoolBook           = schoolBookTheme;
  static const Map<String, TextStyle> stackoverflowLight   = stackoverflowLightTheme;
  static const Map<String, TextStyle> tokyoNightLight      = tokyoNightLightTheme;
  static const Map<String, TextStyle> vs                   = vsTheme;
  static const Map<String, TextStyle> xcode                = xcodeTheme;

  // ── Base16 (175 variaciones) ───────────────────────────────────────────────
  // Acceso: MarkastCodeThemes.base16.dracula

  static const base16 = _Base16Catalog();
}

/// Sub-catálogo de temas Base16 — variaciones del esquema de 16 colores.
final class _Base16Catalog {
  const _Base16Catalog();

  Map<String, TextStyle> get apathy                   => apathyTheme;
  Map<String, TextStyle> get apprentice               => apprenticeTheme;
  Map<String, TextStyle> get ashes                    => ashesTheme;
  Map<String, TextStyle> get atelierCave              => atelierCaveTheme;
  Map<String, TextStyle> get atelierCaveLight         => atelierCaveLightTheme;
  Map<String, TextStyle> get atelierDune              => atelierDuneTheme;
  Map<String, TextStyle> get atelierDuneLight         => atelierDuneLightTheme;
  Map<String, TextStyle> get atelierEstuary           => atelierEstuaryTheme;
  Map<String, TextStyle> get atelierEstuaryLight      => atelierEstuaryLightTheme;
  Map<String, TextStyle> get atelierForest            => atelierForestTheme;
  Map<String, TextStyle> get atelierForestLight       => atelierForestLightTheme;
  Map<String, TextStyle> get atelierHeath             => atelierHeathTheme;
  Map<String, TextStyle> get atelierHeathLight        => atelierHeathLightTheme;
  Map<String, TextStyle> get atelierLakeside          => atelierLakesideTheme;
  Map<String, TextStyle> get atelierLakesideLight     => atelierLakesideLightTheme;
  Map<String, TextStyle> get atelierPlateau           => atelierPlateauTheme;
  Map<String, TextStyle> get atelierPlateauLight      => atelierPlateauLightTheme;
  Map<String, TextStyle> get atelierSavanna           => atelierSavannaTheme;
  Map<String, TextStyle> get atelierSavannaLight      => atelierSavannaLightTheme;
  Map<String, TextStyle> get atelierSeaside           => atelierSeasideTheme;
  Map<String, TextStyle> get atelierSeasideLight      => atelierSeasideLightTheme;
  Map<String, TextStyle> get atelierSulphurpool       => atelierSulphurpoolTheme;
  Map<String, TextStyle> get atelierSulphurpoolLight  => atelierSulphurpoolLightTheme;
  Map<String, TextStyle> get atlas                    => atlasTheme;
  Map<String, TextStyle> get bespin                   => bespinTheme;
  Map<String, TextStyle> get blackMetal               => blackMetalTheme;
  Map<String, TextStyle> get blackMetalBathory        => blackMetalBathoryTheme;
  Map<String, TextStyle> get blackMetalBurzum         => blackMetalBurzumTheme;
  Map<String, TextStyle> get blackMetalDarkFuneral    => blackMetalDarkFuneralTheme;
  Map<String, TextStyle> get blackMetalGorgoroth      => blackMetalGorgorothTheme;
  Map<String, TextStyle> get blackMetalImmortal       => blackMetalImmortalTheme;
  Map<String, TextStyle> get blackMetalKhold          => blackMetalKholdTheme;
  Map<String, TextStyle> get blackMetalMarduk         => blackMetalMardukTheme;
  Map<String, TextStyle> get blackMetalMayhem         => blackMetalMayhemTheme;
  Map<String, TextStyle> get blackMetalNile           => blackMetalNileTheme;
  Map<String, TextStyle> get blackMetalVenom          => blackMetalVenomTheme;
  Map<String, TextStyle> get brewer                   => brewerTheme;
  Map<String, TextStyle> get bright                   => brightTheme;
  Map<String, TextStyle> get brogrammer               => brogrammerTheme;
  Map<String, TextStyle> get brushTrees               => brushTreesTheme;
  Map<String, TextStyle> get brushTreesDark           => brushTreesDarkTheme;
  Map<String, TextStyle> get chalk                    => chalkTheme;
  Map<String, TextStyle> get circus                   => circusTheme;
  Map<String, TextStyle> get classicDark              => classicDarkTheme;
  Map<String, TextStyle> get classicLight             => classicLightTheme;
  Map<String, TextStyle> get codeschool               => codeschoolTheme;
  Map<String, TextStyle> get colors                   => colorsTheme;
  Map<String, TextStyle> get cupcake                  => cupcakeTheme;
  Map<String, TextStyle> get cupertino                => cupertinoTheme;
  Map<String, TextStyle> get danqing                  => danqingTheme;
  Map<String, TextStyle> get darcula                  => darculaTheme;
  Map<String, TextStyle> get darkViolet               => darkVioletTheme;
  Map<String, TextStyle> get darkmoss                 => darkmossTheme;
  Map<String, TextStyle> get darktooth                => darktoothTheme;
  Map<String, TextStyle> get decaf                    => decafTheme;
  Map<String, TextStyle> get defaultDark              => defaultDarkTheme;
  Map<String, TextStyle> get defaultLight             => defaultLightTheme;
  Map<String, TextStyle> get dirtysea                 => dirtyseaTheme;
  Map<String, TextStyle> get dracula                  => draculaTheme;
  Map<String, TextStyle> get edgeDark                 => edgeDarkTheme;
  Map<String, TextStyle> get edgeLight                => edgeLightTheme;
  Map<String, TextStyle> get eighties                 => eightiesTheme;
  Map<String, TextStyle> get embers                   => embersTheme;
  Map<String, TextStyle> get equilibriumDark          => equilibriumDarkTheme;
  Map<String, TextStyle> get equilibriumGrayDark      => equilibriumGrayDarkTheme;
  Map<String, TextStyle> get equilibriumGrayLight     => equilibriumGrayLightTheme;
  Map<String, TextStyle> get equilibriumLight         => equilibriumLightTheme;
  Map<String, TextStyle> get espresso                 => espressoTheme;
  Map<String, TextStyle> get eva                      => evaTheme;
  Map<String, TextStyle> get evaDim                   => evaDimTheme;
  Map<String, TextStyle> get flat                     => flatTheme;
  Map<String, TextStyle> get framer                   => framerTheme;
  Map<String, TextStyle> get fruitSoda                => fruitSodaTheme;
  Map<String, TextStyle> get gigavolt                 => gigavoltTheme;
  Map<String, TextStyle> get github                   => b16_github.githubTheme;
  Map<String, TextStyle> get googleDark               => googleDarkTheme;
  Map<String, TextStyle> get googleLight              => googleLightTheme;
  Map<String, TextStyle> get grayscaleDark            => grayscaleDarkTheme;
  Map<String, TextStyle> get grayscaleLight           => grayscaleLightTheme;
  Map<String, TextStyle> get greenScreen              => greenScreenTheme;
  Map<String, TextStyle> get gruvboxDarkHard          => gruvboxDarkHardTheme;
  Map<String, TextStyle> get gruvboxDarkMedium        => gruvboxDarkMediumTheme;
  Map<String, TextStyle> get gruvboxDarkPale          => gruvboxDarkPaleTheme;
  Map<String, TextStyle> get gruvboxDarkSoft          => gruvboxDarkSoftTheme;
  Map<String, TextStyle> get gruvboxLightHard         => gruvboxLightHardTheme;
  Map<String, TextStyle> get gruvboxLightMedium       => gruvboxLightMediumTheme;
  Map<String, TextStyle> get gruvboxLightSoft         => gruvboxLightSoftTheme;
  Map<String, TextStyle> get hardcore                 => hardcoreTheme;
  Map<String, TextStyle> get harmonic16Dark           => harmonic16DarkTheme;
  Map<String, TextStyle> get harmonic16Light          => harmonic16LightTheme;
  Map<String, TextStyle> get heetchDark               => heetchDarkTheme;
  Map<String, TextStyle> get heetchLight              => heetchLightTheme;
  Map<String, TextStyle> get helios                   => heliosTheme;
  Map<String, TextStyle> get hopscotch                => hopscotchTheme;
  Map<String, TextStyle> get horizonDark              => horizonDarkTheme;
  Map<String, TextStyle> get horizonLight             => horizonLightTheme;
  Map<String, TextStyle> get humanoidDark             => humanoidDarkTheme;
  Map<String, TextStyle> get humanoidLight            => humanoidLightTheme;
  Map<String, TextStyle> get iaDark                   => iaDarkTheme;
  Map<String, TextStyle> get iaLight                  => iaLightTheme;
  Map<String, TextStyle> get icyDark                  => icyDarkTheme;
  Map<String, TextStyle> get irBlack                  => b16_ir_black.irBlackTheme;
  Map<String, TextStyle> get isotope                  => isotopeTheme;
  Map<String, TextStyle> get kimber                   => kimberTheme;
  Map<String, TextStyle> get londonTube               => londonTubeTheme;
  Map<String, TextStyle> get macintosh                => macintoshTheme;
  Map<String, TextStyle> get marrakesh                => marrakeshTheme;
  Map<String, TextStyle> get materia                  => materiaTheme;
  Map<String, TextStyle> get material                 => materialTheme;
  Map<String, TextStyle> get materialDarker           => materialDarkerTheme;
  Map<String, TextStyle> get materialLighter          => materialLighterTheme;
  Map<String, TextStyle> get materialPalenight        => materialPalenightTheme;
  Map<String, TextStyle> get materialVivid            => materialVividTheme;
  Map<String, TextStyle> get mellowPurple             => mellowPurpleTheme;
  Map<String, TextStyle> get mexicoLight              => mexicoLightTheme;
  Map<String, TextStyle> get mocha                    => mochaTheme;
  Map<String, TextStyle> get monokai                  => b16_monokai.monokaiTheme;
  Map<String, TextStyle> get nebula                   => nebulaTheme;
  Map<String, TextStyle> get nord                     => b16_nord.nordTheme;
  Map<String, TextStyle> get nova                     => novaTheme;
  Map<String, TextStyle> get ocean                    => oceanTheme;
  Map<String, TextStyle> get oceanicnext              => oceanicnextTheme;
  Map<String, TextStyle> get onedark                  => onedarkTheme;
  Map<String, TextStyle> get oneLight                 => oneLightTheme;
  Map<String, TextStyle> get outrunDark               => outrunDarkTheme;
  Map<String, TextStyle> get papercolorDark           => papercolorDarkTheme;
  Map<String, TextStyle> get papercolorLight          => papercolorLightTheme;
  Map<String, TextStyle> get paraiso                  => paraisoTheme;
  Map<String, TextStyle> get pasque                   => pasqueTheme;
  Map<String, TextStyle> get phd                      => phdTheme;
  Map<String, TextStyle> get pico                     => picoTheme;
  Map<String, TextStyle> get pop                      => popTheme;
  Map<String, TextStyle> get porple                   => porpleTheme;
  Map<String, TextStyle> get qualia                   => qualiaTheme;
  Map<String, TextStyle> get railscasts               => railscastsTheme;
  Map<String, TextStyle> get rebecca                  => rebeccaTheme;
  Map<String, TextStyle> get rosPine                  => rosPineTheme;
  Map<String, TextStyle> get rosPineDawn              => rosPineDawnTheme;
  Map<String, TextStyle> get rosPineMoon              => rosPineMoonTheme;
  Map<String, TextStyle> get sagelight                => sagelightTheme;
  Map<String, TextStyle> get sandcastle               => sandcastleTheme;
  Map<String, TextStyle> get setiUi                   => setiUiTheme;
  Map<String, TextStyle> get shapeshifter             => shapeshifterTheme;
  Map<String, TextStyle> get silkDark                 => silkDarkTheme;
  Map<String, TextStyle> get silkLight                => silkLightTheme;
  Map<String, TextStyle> get snazzy                   => snazzyTheme;
  Map<String, TextStyle> get solarFlare               => solarFlareTheme;
  Map<String, TextStyle> get solarFlareLight          => solarFlareLightTheme;
  Map<String, TextStyle> get solarizedDark            => solarizedDarkTheme;
  Map<String, TextStyle> get solarizedLight           => solarizedLightTheme;
  Map<String, TextStyle> get spacemacs                => spacemacsTheme;
  Map<String, TextStyle> get summercamp               => summercampTheme;
  Map<String, TextStyle> get summerfruitDark          => summerfruitDarkTheme;
  Map<String, TextStyle> get summerfruitLight         => summerfruitLightTheme;
  Map<String, TextStyle> get synthMidnightDark        => synthMidnightTerminalDarkTheme;
  Map<String, TextStyle> get synthMidnightLight       => synthMidnightTerminalLightTheme;
  Map<String, TextStyle> get tango                    => tangoTheme;
  Map<String, TextStyle> get tender                   => tenderTheme;
  Map<String, TextStyle> get tomorrow                 => tomorrowTheme;
  Map<String, TextStyle> get tomorrowNight            => tomorrowNightTheme;
  Map<String, TextStyle> get twilight                 => twilightTheme;
  Map<String, TextStyle> get unikittyDark             => unikittyDarkTheme;
  Map<String, TextStyle> get unikittyLight            => unikittyLightTheme;
  Map<String, TextStyle> get vulcan                   => vulcanTheme;
  Map<String, TextStyle> get windows10               => windows10Theme;
  Map<String, TextStyle> get windows10Light          => windows10LightTheme;
  Map<String, TextStyle> get windows95               => windows95Theme;
  Map<String, TextStyle> get windows95Light          => windows95LightTheme;
  Map<String, TextStyle> get windowsHighContrast     => windowsHighContrastTheme;
  Map<String, TextStyle> get windowsHighContrastLight => windowsHighContrastLightTheme;
  Map<String, TextStyle> get windowsNt               => windowsNtTheme;
  Map<String, TextStyle> get windowsNtLight          => windowsNtLightTheme;
  Map<String, TextStyle> get woodland                 => woodlandTheme;
  Map<String, TextStyle> get xcodeDusk               => xcodeDuskTheme;
  Map<String, TextStyle> get zenburn                  => zenburnTheme;
}
